# Generated by Django 5.1.1 on 2024-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категорий')),
                ('icon', models.ImageField(upload_to='category/icon', verbose_name='Иконка')),
                ('icon_mobile', models.ImageField(upload_to='category/icon_mobile', verbose_name='Иконка')),
            ],
        ),
    ]
